name: Daily Random Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make random change
        run: |
          echo "Random change at $(date)" >> random_change.txt

      - name: Commit changes
        run: |
          git config --local user.email "afzaalk137@gmail.com"
          git config --local user.name "MdAfzaalkhan"
          git add random_change.txt
          git commit -m "Daily random commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/MdAfzaalkhan/weather-using-skia-reanimated.git HEAD:main
